name = "arabic-vocabulary"
compatibility_date = "2025-01-01"
account_id = "722a276f61c1955a2fc6a75b6437d74c"

# Serve this folder as the site root
pages_build_output_dir = "knowledge-map-ui/dist/knowledge-map-ui/browser"

[[d1_databases]]
binding = "DB"
database_name = "knowledgemap"
database_id = "ef164d27-6e98-41c5-beca-03903d658976"


# npx wrangler pages deploy
